---
title: "Diamonds_investigation"
output: html_document
editor_options: 
  chunk_output_type: console
---
# read in data

```{r}
getwd()
setwd("/Users/geodev/code/daan-nano/term2/EDA/lesson4")
list.files()
library(ggplot2)
data(diamonds)
summary(diamonds)
names(diamonds)
str(diamonds)
```

# histogram of all diamond prices
```{r}
priceHist <- ggplot(aes(x = price), data = diamonds) +
  geom_histogram(color = 'black', fill = 'red') +
  scale_x_continuous(limits = c(0,20000), breaks = seq(0,20000,2500)) + 
  labs(x = "diamond price", y = "nb of diamonds") +
  scale_x_log10()
# arrange plots in grid
grid.arrange(priceHist, ncol=1)
```

# count of diamonds by price
```{r}
sum(diamonds$price < 500)
sum(diamonds$price < 250)
sum(diamonds$price >= 15000)
```

# explore largest peak
```{r}
priceHist <- ggplot(aes(x = price), data = diamonds) +
  geom_histogram(binwidth = 25, color = 'black', fill = 'red') +
  labs(x = "diamond price", y = "nb of diamonds") +
  scale_x_continuous(limits = c(0,1500), breaks = seq(0, 1500, 250)) #+ 
  #scale_x_log10()
# arrange plots in grid
grid.arrange(priceHist, ncol=1)
```

# histogram of diamonds by cut
```{r}
ggplot(aes(x = price), data = diamonds) +
  geom_histogram(aes(fill = cut)) +
  scale_x_log10() +
  facet_wrap(~color, scales = 'free_y')
```
```{r}
by(diamonds$price, diamonds$cut, summary)
```

```{r}
qplot(x = price, data = diamonds) + facet_wrap(~cut, scales = 'free_y')
```

# histogram of diamonds by cut
```{r}
ggplot(aes(x = price), data = diamonds) +
  geom_histogram(aes(fill = cut)) +
  scale_x_log10() +
  facet_wrap(~color, scales = 'free_y')
```

# boxplots price by cut
```{r}
# get names
names(diamonds)
# plot data using boxplot
qplot(x = cut, y = price, 
      data = diamonds, 
      geom = 'boxplot') +
  coord_cartesian(ylim = c(0,7500))

#by(diamonds$price, diamonds$cut, summary)
```

# boxplots price by clarity
```{r}
# get names
names(diamonds)
# plot data using boxplot
qplot(x = clarity, y = price, 
      data = diamonds, 
      geom = 'boxplot') +
  coord_cartesian(ylim = c(0,7500))

#by(diamonds$price, diamonds$clarity, summary)
```

# boxplots price by color
```{r}
# get names
names(diamonds)
# plot data using boxplot
qplot(x = color, y = price, 
      data = diamonds, 
      geom = 'boxplot') +
  coord_cartesian(ylim = c(0,7500))

by(diamonds$price, diamonds$color, summary)
```

# frequency polygons of www_likes
```{r}
qplot(x = carat, 
      data = diamonds,
      xlab = 'carat',
      ylab = 'Count of diamonds with given carat',
      geom = 'freqpoly',
      color = carat,
      binwidth = 0.1) +
  scale_y_continuous(limits = c(0,12000), breaks = seq(0, 12000, 1000)) +
  scale_x_continuous(limits = c(0,5), breaks = seq(0,5,.1)) #+
  #scale_x_log10()
```
